### ISSUE TITLE
Plugin requirement test fails with error

### ISSUE THREAD

**Issue by samsch** [Centillien/elgg_social_login#5]
I'm attempting to install this plugin in an Elgg 2.3.1 install.

I downloaded the plugin from the plugin page [https://elgg.org/plugins/1440827](https://elgg.org/plugins/1440827). I unzipped and inserted the folder into `/<project-path>/mod/`. In the admin plugin view, I'm given the option to activate Social Login, so the installation appears to be correct.

I go to the plugin settings page, and run the plugin requirements test, which gives me two PHP errors:
```
Warning: require_once(/srv/app/web/engine/start.php): failed to open stream: No such file or directory in /srv/app/web/mod/elgg_social_login/diagnostics.php on line 2
```
```
Fatal error: require_once(): Failed opening required '/srv/app/web/engine/start.php' (include_path='.:/usr/local/lib/php') in /srv/app/web/mod/elgg_social_login/diagnostics.php on line 2
```

Looking at the code, it looks like diagnostics.php assumes that it is in `vendor/elgg/elgg/mod/elgg_social_login/`, and attempts to access `vendor/elgg/elgg/engine/start.php`.

This is my first time running Elgg, so I'm not sure if this could stem from differences between v1 and v2.

**Comment by gerard-kanters** [comment]
Hi Samuel, this plugin is not maintained anymore and it has not been upgraded to elgg 2.3 

It seems that you are running elgg in a starter project. That is the reason it cannot find the required module. This is recommended though, since you can use composer properly. 

My suggestion is to use a different plugin for social login.
